In [28]:
# first, I want to generate a set of valid tuples
# we need a list of valid tuples (sentence_out, intermediates)
# simplest case, all segments are (B, B, T)
# for arbitrary T, since B is universal in depth-2
from gulps.core import GateInvariants
from qiskit.quantum_info.random import random_unitary
from gulps.synthesis.segments_abc import SegmentSolver, SegmentSolution
import qutip as qt

In [29]:
# for now, this is just a sanity check because its simplest way to generate valid segments
prefix_op = GateInvariants.from_weyl(coords=(0.5, 0.25, 0)).canonical_matrix
basis_gate = B = GateInvariants.from_weyl(coords=(0.5, 0.25, 0)).canonical_matrix
target = GateInvariants.from_unitary(random_unitary(4)).canonical_matrix

In [30]:
from gulps.synthesis.jax_lm import JaxLMSegmentSolver

jax_solver = JaxLMSegmentSolver()
jax_solver.solve_segment(prefix_op, basis_gate, target)

SegmentSolution(u0=array([[-0.96972257+0.20173324j, -0.12875801-0.04861294j],
       [ 0.12875801-0.04861294j, -0.96972257-0.20173324j]]), u1=array([[ 0.52050644+0.5989458j ,  0.29249584-0.53365079j],
       [-0.29249584-0.53365079j,  0.52050644-0.5989458j ]]), residual_norm=2.469337472885363e-32, success=True, metadata={'label': 'easy', 'attempt': 1, 'nfev': 12, 'elapsed': 1.1908299759961665})

In [31]:
import numpy as np

U = target
MAGIC = np.array(
    [[1, 0, 0, 1j], [0, 1j, 1, 0], [0, 1j, -1, 0], [1, 0, 0, -1j]],
    dtype=np.cdouble,
) / np.sqrt(2)
Um = MAGIC.conj().T.dot(U.dot(MAGIC))
qt.Qobj(Um)

Quantum object: dims=[[4], [4]], shape=(4, 4), type='oper', dtype=Dense, isherm=False
Qobj data =
[[ 7.97614183e-01+6.03167982e-01j  0.00000000e+00+0.00000000e+00j
   0.00000000e+00+0.00000000e+00j -5.11890598e-17+2.54050890e-17j]
 [ 0.00000000e+00+0.00000000e+00j  6.68388367e-01+7.43812471e-01j
   5.96149225e-17+1.20192200e-16j  0.00000000e+00+0.00000000e+00j]
 [ 0.00000000e+00+0.00000000e+00j -1.28284662e-17-1.11661382e-16j
   4.87531185e-01-8.73105574e-01j  0.00000000e+00+0.00000000e+00j]
 [ 2.14704164e-17+9.61889828e-18j  0.00000000e+00+0.00000000e+00j
   0.00000000e+00+0.00000000e+00j  9.11167773e-01-4.12035544e-01j]]

In [19]:
import numpy as np
from qiskit.quantum_info import random_unitary

u0 = random_unitary(2).data
u1 = random_unitary(2).data

# Remove global phases
u0 /= np.linalg.det(u0) ** (1 / 2)
u1 /= np.linalg.det(u1) ** (1 / 2)

U = np.kron(u0, u1)
Um = MAGIC.conj().T @ U @ MAGIC

qt.Qobj(Um.T @ Um)

Quantum object: dims=[[4], [4]], shape=(4, 4), type='oper', dtype=Dense, isherm=True
Qobj data =
[[ 1.00000000e+00 -1.10153317e-17  2.84002527e-17  1.24874948e-17]
 [-1.10153317e-17  1.00000000e+00  2.92216001e-17 -8.01780717e-18]
 [ 2.84002527e-17  2.92216001e-17  1.00000000e+00  8.86117347e-18]
 [ 1.24874948e-17 -8.01780717e-18  8.86117347e-18  1.00000000e+00]]

In [71]:
GateInvariants.from_weyl(coords=(0.5, 0.25, 0)).logspec

(np.float64(0.375), np.float64(0.125), np.float64(-0.125), np.float64(-0.375))

In [74]:
np.exp(2 * np.pi * 1j * 0.375)

np.complex128(-0.7071067811865475+0.7071067811865476j)

In [68]:
np.exp(np.pi / 2 * 1j * (0.5 + 0.25))

np.complex128(0.38268343236508984+0.9238795325112867j)

In [6]:
class ConstructiveSegmentSolver(SegmentSolver):
    def __init__(self):
        pass

    def solve_segment(self, prefix_op, basis_gate, target, *, rng_seed=None):
        return SegmentSolution(
            u0=None, u1=None, residual_norm=0.0, success=False, metadata={}
        )

In [7]:
constructive_solver = ConstructiveSegmentSolver()
constructive_solver.solve_segment(prefix_op, basis_gate, target)

SegmentSolution(u0=None, u1=None, residual_norm=0.0, success=False, metadata={})